import streamlit as st
import requests

# --- Cloudflare Configuration (Alpha Private Access) ---
# ඔබ ලබා දුන් දත්ත මෙහි ඇතුළත් කර ඇත
CLOUDFLARE_ACCOUNT_ID = "2974b71a6d3dab87c1216cfd085422c5"
CLOUDFLARE_API_TOKEN = "p4kEdb7MYrPDFbknGZQEw4aMIiIrMrrzLabJux6x" # ඔබේ Token එක මම මෙහි නිවැරදිව ඇතුළත් කළා

def generate_image(prompt):
    # Cloudflare AI API URL (SDXL Lightning Model)
    url = f"https://api.cloudflare.com/client/v4/accounts/{CLOUDFLARE_ACCOUNT_ID}/ai/run/@cf/bytedance/stable-diffusion-xl-lightning"
    
    headers = {
        "Authorization": f"Bearer {CLOUDFLARE_API_TOKEN}",
        "Content-Type": "application/json"
    }
    
    # AI එකට යවන දත්ත
    payload = {"prompt": prompt}
    
    try:
        response = requests.post(url, headers=headers, json=payload)
        
        if response.status_code == 200:
            return response.content
        else:
            # Error එකක් ආවොත් ඒක විස්තරාත්මකව පෙන්වන්න
            return f"Error: {response.status_code} - {response.text}"
    except Exception as e:
        return f"සම්බන්ධතාවයේ දෝෂයකි: {str(e)}"

# --- Alpha AI Interface ---
st.set_page_config(page_title="Alpha Pro AI", page_icon="🛡️")

# ඇප් එකේ පෙනුම
st.title("🛡️ Alpha Private Photo Lab")
st.markdown("Cloudflare Private API මගින් බලගන්වන සුපිරි වේගවත් AI එන්ජිම.")

# User Input
prompt_input = st.text_input("ඔබට අවශ්‍ය පින්තූරය ගැන විස්තර කරන්න (English වලින්):", placeholder="e.g. A realistic Transformers robot in Ella Sri Lanka mountain")

# Generate Button
if st.button("Generate Image 🚀"):
    if prompt_input:
        with st.spinner("Alpha Engine වැඩ කරයි. කරුණාකර තත්පර 2-5ක් රැඳී සිටින්න..."):
            result = generate_image(prompt_input)
            
            # ප්‍රතිඵලය පින්තූරයක් නම් එය පෙන්වන්න
            if isinstance(result, bytes):
                st.image(result, caption="Generated by Alpha AI", use_container_width=True)
                st.success("වැඩේ සාර්ථකයි! (Cloudflare Lightning Engine)")
            else:
                st.error(result)
                st.info("සටහන: Token එකේ Permissions වල Workers AI Edit දීලා නැත්නම් විතරක් 401 Error එක එන්න පුළුවන්.")
    else:
        st.warning("කරුණාකර යමක් ලියන්න!")

# --- Footer ---
st.divider()
st.caption("Alpha AI Technology | Powered by Cloudflare Workers AI")
