import streamlit as st
import requests
import io

# 
API_KEY = "sk-jwcbzyfeqvklmbgbqtksrugwbuulrknkthlmaaesxcdefntl"

def generate_image(prompt):
    url = "https://api.siliconflow.cn/v1/images/generations"
    
    headers = {
        "Authorization": f"Bearer {API_KEY}",
        "Content-Type": "application/json"
    }
    
    payload = {
        "model": "stabilityai/stable-diffusion-xl-base-1.0",
        "prompt": prompt,
        "negative_prompt": "blurry, low quality, distorted",
        "image_size": "1024x1024",
        "batch_size": 1
    }
    
    response = requests.post(url, json=payload, headers=headers)
    
    if response.status_code == 200:
        # SiliconFlow අපිට දෙන්නේ පින්තූරයේ URL එකයි
        return response.json()['data'][0]['url']
    else:
        return f"දෝෂයකි: {response.status_code} - {response.text}"

st.set_page_config(page_title="Alpha Ultra AI", page_icon="🛡️")
st.title("🛡️ Alpha Private Ultra Lab")
st.write("මෙය SiliconFlow සුපිරි පරිගණක මගින් ක්‍රියාත්මක වේ. (පෝලිම් නැත)")

user_input = st.text_input("රූපය ගැන ලියන්න (English):", placeholder="A Transformers robot in Sri Lanka mountain")

if st.button("Generate Image 🚀"):
    if user_input:
        with st.spinner("Alpha Engine තත්පරයකින් පින්තූරය සාදයි..."):
            result = generate_image(user_input)
            if result.startswith("http"):
                st.image(result, caption="Generated by Alpha AI", use_container_width=True)
                st.success("වැඩේ සුපිරියටම සාර්ථකයි!")
            else:
                st.error(result)
    else:
        st.warning("කරුණාකර යමක් ලියන්න!")
