import streamlit as st
import requests
import base64
from PIL import Image
from io import BytesIO

# --- Page Config (ඇප් එකේ නම සහ අයිකනය) ---
st.set_page_config(page_title="Alpha Photo Lab", page_icon="📸", layout="wide")

# --- Groq AI හරහා Prompt එක Enhance කරන Function එක ---
def improve_prompt(user_query):
    # ඔබේ Groq API Key එක මෙතැනට දාන්න
    GROQ_API_KEY = "ඔබේ_GROQ_KEY_එක" 
    url = "https://api.groq.com/openai/v1/chat/completions"
    
    headers = {
        "Authorization": f"Bearer {GROQ_API_KEY}",
        "Content-Type": "application/json"
    }
    
    # AI එකට උපදෙස් දීම (Prompt Engineering)
    system_prompt = "You are a professional SDXL prompt engineer. Rewrite the user's input into a highly detailed, cinematic, and artistic image prompt. Only output the final prompt."
    
    data = {
        "model": "llama3-70b-8192", 
        "messages": [
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": user_input}
        ]
    }
    
    try:
        res = requests.post(url, json=data, headers=headers, timeout=10)
        return res.json()['choices'][0]['message']['content']
    except:
        return user_query # Error එකක් වුණොත් මුල් එකම යවනවා

# --- ප්‍රධාන UI එක ---
st.title("🛡️ Alpha Unlimited Photo Lab")
st.markdown("---")

# ඔබේ HuggingFace Server URL එක
SERVER_URL = "https://sanjayali-alpha-sdl-server.hf.space/generate"

# Input කොටස
user_input = st.text_input("ඔබේ හිතේ තියෙන රූපය ගැන මෙතැන ලියන්න:", placeholder="A majestic lion king with a golden crown, cinematic 8k...")

# විකල්ප (Options) ටිකක් එකතු කරමු
col1, col2 = st.columns(2)
with col1:
    style = st.selectbox("Style එක තෝරන්න:", ["Cinematic", "Anime", "3D Render", "Oil Painting", "Cyberpunk", "Realistic"])
with col2:
    enhance = st.checkbox("Groq AI හරහා Prompt එක ලස්සන කරන්න", value=True)

if st.button("Generate Image 🚀"):
    if user_input:
        with st.spinner("Alpha Engine වැඩ කරමින් පවතී... පොඩ්ඩක් ඉන්න..."):
            
            # 1. Prompt එක Enhance කිරීම (Checkbox එක On නම්)
            final_prompt = f"{user_input}, style: {style}"
            if enhance:
                final_prompt = improve_prompt(final_prompt)
                st.info(f"✨ Optimized Prompt: {final_prompt}")
            
            # 2. ඔබේ HuggingFace Server එකට Data යැවීම
            try:
                response = requests.post(SERVER_URL, json={"prompt": final_prompt}, timeout=300)
                
                if response.status_code == 200:
                    # ලැබුණු Base64 රූපය Decode කිරීම
                    img_base64 = response.json()["image"]
                    image_data = base64.b64decode(img_base64)
                    image = Image.open(BytesIO(image_data))
                    
                    # රූපය පෙන්වීම
                    st.image(image, caption="Generated by Alpha Photo Lab", use_container_width=True)
                    
                    # Download කරන්න බටන් එකක්
                    st.download_button(label="Download Image", data=image_data, file_name="alpha_gen.png", mime="image/png")
                else:
                    st.error(f"සර්වර් එකේ ගැටලුවක් (Code: {response.status_code}). සර්වර් එක 'Running' ද කියා පරීක්ෂා කරන්න.")
            
            except Exception as e:
                st.error(f"සම්බන්ධතාවයේ බාධාවක්: {e}")
    else:
        st.warning("කරුණාකර යම් දෙයක් ලියන්න!")

st.markdown("---")
st.caption("Powered by Alpha Engine | Developed by Hasith")
